# Prod environment: pull policy (image tag managed via kustomization.yaml images)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rayuela
spec:
  template:
    spec:
      containers:
        - name: rayuela
          imagePullPolicy: IfNotPresent
