-- =============================================================================
-- Production Database - Tenant 2 (grext2)
-- =============================================================================
-- This file is intentionally empty.
-- 
-- Production deployment only uses a single organization (Obispado de Cruz del Eje)
-- which is stored in grext1. Organization 2 and its tenant database are not used
-- in production.
--
-- If a second organization is needed in the future, add its data here following
-- the UUID pattern: 10000000-0000-0000-TTTT-NNNNNNNNNNNN
-- =============================================================================
