apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rayuela-db
  labels:
    app.kubernetes.io/name: rayuela-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: rayuela
spec:
  replicas: 1
  serviceName: rayuela-db
  selector:
    matchLabels:
      app.kubernetes.io/name: rayuela-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rayuela-db
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: rayuela
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:17-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: grex
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rayuela-db
                  key: password
            - name: POSTGRES_DB
              value: grexc
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_INITDB_ARGS
              value: "--locale-provider=icu --icu-locale=en-US"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - grex
                - -d
                - grexc
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - grex
                - -d
                - grexc
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: init-scripts
          configMap:
            name: rayuela-db-init
            defaultMode: 0755
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: rayuela-storage
        resources:
          requests:
            storage: 5Gi
