---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rayuela-backup-secrets
  namespace: rayuela-prod
spec:
  encryptedData:
    restic-password: AgCG4RSfKZkqWAYEpBqUWp96WVbjmpLtt6Bocu/6qOUx9XqJK/SM5D8MpX/5L+6SNsSosyc9uy55ZkvBm4RcLcmIL/+ODLT8VWNP4kf6/mes42fyaFkWuZ6AjD2q8MD/QAWLkyMQV/0u+NnOQFhLLkPV7L/4OfNtbpPMdO3oAdbniQ5IJbitCUNgDLmRSvyvXd3qVpVhTJ07JO9t2PJCB5foZhPgL5mQ1VyPoZjflt/bVrJL6HmNCDfwXUqzXSb0sKSf6mlSyGSA9OWd+xO0DJANk3hhcEZZ/540W45gsbywy9UKM/FobtUmRQQhGxSuiUwKvYOX4rVpYB2xpQYRCkctnZSxRqWfCtYLX1qp4VFS+TOOaXi8DWEAo7rSRJWwu+JM8gz6fR2GWfDGpIbfojW8Zgwbt1JUeXvHm5ApZB8a7ECw6vi3RM+ZkmE2YFvLyYqtStnWfndxPu/CM44H3V1Je8X00H85M/MDFvJw8F5g7IpxP0zD193STkoCUHh9WXWHDB5yqzE9JGRNHhCzWUuZFKYgN2hiK+VouvJklhSahx7IGMFtAWZyg38qxl31HOkIdcXqjRHCRhVlDU3uZoHpSFa64xBPm6BelUMW/4MVf4JMms7PzN8WUfUlTtLo7dcjd8ehh6gLsJ04G+XF6vgTjIwzyccjeE6rozzZH2jNNNkLhl2ObtMSdhy71XKajkadOO0bODsdkxlAdGFGEE6M7ACMW7Fwrn9D
  template:
    metadata:
      creationTimestamp: null
      name: rayuela-backup-secrets
      namespace: rayuela-prod
