---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rayuela-backup-secrets
  namespace: rayuela-prod
spec:
  encryptedData:
    restic-password: AgAJQp79MHgKFQtTDYEGLcyRB7JneA88RNFH29Kv8zv21R0JiPWM9YOEyNuXjpVX4MF+jgy7TaRyPWWgocpsa02Q/QJS6JB5XtTeAZyhlVCPxb1Bift93h6AmWVlu+cRMMhYx7HSujwl6VTZ3R6r+e8xgTNRP6gnbaWH9bSkHDM/lDB02LL15O77+G2Ch8k26n3wqyTJmm/PuX8WbWHXfczhFZ2BAayBzZsRHt1ZeYI6eNp70z30yl64fCSR5znX8D6JHPGw9+u+SfH6OLf6rsChXTfnzjBkI23H3yYa+/W2VBX9debSG+bjL0joGqP3j0Ubyo+aZs4EE4Toy0Xa5DKUSIjNzE4+q4mUAhHHWkmzX4boqFb0NanruXIROmkNExifMffnCsQG+EHUR+tw4eGWdlQ6z6jHu6wc+Q743FezMCvWIKiY4kCwXEMPAXnuNQD2bIA8iDjN4SwaXr7Q6BfDLvxvRHovhjVqXdIo4HrYMtV5Tm8a4bkKbqa7Shs/L2T7P+ZcBSAh5TvtAtoQF2N5aFOhtUVmjKtsLX7X3c7SFV7TSy6Rzg8T1vr+llisa6bSazQxWICVhqRwk52lo65IIQw2VdZwF0urrlhCSor1nTttkpK+ccFh83H2X+d0wcc0eQmFwo41WcjHvrucj2S7g+8djMtlEopcPWTXa2sSnpDf+O/sNOasiOH9BxWQnl32/gKXO9q9Vcey9UVhuzuZVs+PEnq0AUHn
  template:
    metadata:
      name: rayuela-backup-secrets
      namespace: rayuela-prod
