# PLACEHOLDER - This file needs to be sealed with your cluster's public key
#
# To seal this secret:
#   1. Install sealed-secrets controller: kubectl apply -k infra/sealed-secrets
#   2. Run: ./scripts/seal-secret.sh dev
#
# The script will prompt for values and replace this file with a properly sealed secret.
#
# DO NOT commit real credentials to this file!

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rayuela-secrets
  namespace: rayuela
spec:
  encryptedData:
    # Database password - PLACEHOLDER
    db-password: PLACEHOLDER_RUN_SEAL_SECRET_SH
    # OAuth2/OIDC credentials - PLACEHOLDER (optional)
    oidc-client-id: PLACEHOLDER_RUN_SEAL_SECRET_SH
    oidc-client-secret: PLACEHOLDER_RUN_SEAL_SECRET_SH
  template:
    metadata:
      name: rayuela-secrets
      namespace: rayuela
      labels:
        app.kubernetes.io/name: rayuela
        app.kubernetes.io/component: secrets
        app.kubernetes.io/part-of: rayuela
    type: Opaque
