-- =============================================================================
-- Production Seed Data - Tenant 2 Schema (rayuela database)
-- =============================================================================
-- This file is intentionally empty.
-- 
-- Production deployment only uses a single organization (Obispado de Cruz del Eje).
-- If a second organization is needed in the future, add its data here with
-- SET search_path = 'tenant_{uuid}'; at the top.
-- =============================================================================
