apiVersion: v1
kind: Service
metadata:
  name: rayuela-db
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: rayela-db
  type: ClusterIP
  sessionAffinity: None
