# Dev environment: smaller resources, single replica
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rayuela
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rayuela
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
